// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AuthorsColumns holds the columns for the "authors" table.
	AuthorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "active", Type: field.TypeBool, Default: true},
	}
	// AuthorsTable holds the schema information for the "authors" table.
	AuthorsTable = &schema.Table{
		Name:       "authors",
		Columns:    AuthorsColumns,
		PrimaryKey: []*schema.Column{AuthorsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "authors_users_author",
				Columns:    []*schema.Column{AuthorsColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// BooksColumns holds the columns for the "books" table.
	BooksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "pages", Type: field.TypeInt, Default: 0},
		{Name: "published", Type: field.TypeBool, Default: false},
		{Name: "published_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "internal_notes", Type: field.TypeString, Nullable: true},
		{Name: "book_author", Type: field.TypeInt},
	}
	// BooksTable holds the schema information for the "books" table.
	BooksTable = &schema.Table{
		Name:       "books",
		Columns:    BooksColumns,
		PrimaryKey: []*schema.Column{BooksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "books_authors_author",
				Columns:    []*schema.Column{BooksColumns[7]},
				RefColumns: []*schema.Column{AuthorsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PermissionsColumns holds the columns for the "permissions" table.
	PermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
	}
	// PermissionsTable holds the schema information for the "permissions" table.
	PermissionsTable = &schema.Table{
		Name:       "permissions",
		Columns:    PermissionsColumns,
		PrimaryKey: []*schema.Column{PermissionsColumns[0]},
	}
	// PermissionGroupsColumns holds the columns for the "permission_groups" table.
	PermissionGroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
	}
	// PermissionGroupsTable holds the schema information for the "permission_groups" table.
	PermissionGroupsTable = &schema.Table{
		Name:       "permission_groups",
		Columns:    PermissionGroupsColumns,
		PrimaryKey: []*schema.Column{PermissionGroupsColumns[0]},
	}
	// ReviewsColumns holds the columns for the "reviews" table.
	ReviewsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "rating", Type: field.TypeInt},
		{Name: "body", Type: field.TypeString, Nullable: true},
		{Name: "book_reviews", Type: field.TypeInt},
		{Name: "user_reviews", Type: field.TypeInt},
	}
	// ReviewsTable holds the schema information for the "reviews" table.
	ReviewsTable = &schema.Table{
		Name:       "reviews",
		Columns:    ReviewsColumns,
		PrimaryKey: []*schema.Column{ReviewsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "reviews_books_reviews",
				Columns:    []*schema.Column{ReviewsColumns[3]},
				RefColumns: []*schema.Column{BooksColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "reviews_users_reviews",
				Columns:    []*schema.Column{ReviewsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString, Nullable: true},
		{Name: "is_staff", Type: field.TypeBool, Default: false},
		{Name: "is_superuser", Type: field.TypeBool, Default: false},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "last_login", Type: field.TypeTime, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// PermissionGroupPermissionsColumns holds the columns for the "permission_group_permissions" table.
	PermissionGroupPermissionsColumns = []*schema.Column{
		{Name: "permission_group_id", Type: field.TypeInt},
		{Name: "permission_id", Type: field.TypeInt},
	}
	// PermissionGroupPermissionsTable holds the schema information for the "permission_group_permissions" table.
	PermissionGroupPermissionsTable = &schema.Table{
		Name:       "permission_group_permissions",
		Columns:    PermissionGroupPermissionsColumns,
		PrimaryKey: []*schema.Column{PermissionGroupPermissionsColumns[0], PermissionGroupPermissionsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "permission_group_permissions_permission_group_id",
				Columns:    []*schema.Column{PermissionGroupPermissionsColumns[0]},
				RefColumns: []*schema.Column{PermissionGroupsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "permission_group_permissions_permission_id",
				Columns:    []*schema.Column{PermissionGroupPermissionsColumns[1]},
				RefColumns: []*schema.Column{PermissionsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// UserGroupsColumns holds the columns for the "user_groups" table.
	UserGroupsColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "permission_group_id", Type: field.TypeInt},
	}
	// UserGroupsTable holds the schema information for the "user_groups" table.
	UserGroupsTable = &schema.Table{
		Name:       "user_groups",
		Columns:    UserGroupsColumns,
		PrimaryKey: []*schema.Column{UserGroupsColumns[0], UserGroupsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_groups_user_id",
				Columns:    []*schema.Column{UserGroupsColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_groups_permission_group_id",
				Columns:    []*schema.Column{UserGroupsColumns[1]},
				RefColumns: []*schema.Column{PermissionGroupsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AuthorsTable,
		BooksTable,
		PermissionsTable,
		PermissionGroupsTable,
		ReviewsTable,
		UsersTable,
		PermissionGroupPermissionsTable,
		UserGroupsTable,
	}
)

func init() {
	AuthorsTable.ForeignKeys[0].RefTable = UsersTable
	BooksTable.ForeignKeys[0].RefTable = AuthorsTable
	ReviewsTable.ForeignKeys[0].RefTable = BooksTable
	ReviewsTable.ForeignKeys[1].RefTable = UsersTable
	PermissionGroupPermissionsTable.ForeignKeys[0].RefTable = PermissionGroupsTable
	PermissionGroupPermissionsTable.ForeignKeys[1].RefTable = PermissionsTable
	UserGroupsTable.ForeignKeys[0].RefTable = UsersTable
	UserGroupsTable.ForeignKeys[1].RefTable = PermissionGroupsTable
}
