// Code generated by ent, DO NOT EDIT.

package ent

import "net/http"

func NewVentHandler(client *Client) http.Handler {
	handler := &ventHandler{
		ServeMux: http.NewServeMux(),
		client:   client,
	}

	handler.HandleFunc("/groups/", handler.ventGetGroups)

	handler.HandleFunc("/permissions/", handler.ventGetPermissions)

	handler.HandleFunc("/users/", handler.ventGetUsers)

	return handler
}

type ventHandler struct {
	*http.ServeMux
	client *Client
}

func (handler *ventHandler) ventGetGroups(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	query := handler.client.Group.Query()
	results, err := query.All(ctx)
	if err != nil {
		panic(err)
	}
	print(results)
	w.WriteHeader(200)
}

func (handler *ventHandler) ventGetPermissions(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	query := handler.client.Permission.Query()
	results, err := query.All(ctx)
	if err != nil {
		panic(err)
	}
	print(results)
	w.WriteHeader(200)
}

func (handler *ventHandler) ventGetUsers(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	query := handler.client.User.Query()
	results, err := query.All(ctx)
	if err != nil {
		panic(err)
	}
	print(results)
	w.WriteHeader(200)
}
