// Code generated by vent, DO NOT EDIT.

package admin

import (
	"context"

	"entgo.io/ent/dialect"
	ent "github.com/troygilman/vent/examples/basic/ent"
	"github.com/troygilman/vent/migrategen"
)

var permissions = []struct {
	Name   string
	Schema string
}{
	{Name: "read_author", Schema: "Author"},
	{Name: "create_author", Schema: "Author"},
	{Name: "update_author", Schema: "Author"},
	{Name: "delete_author", Schema: "Author"},
	{Name: "read_book", Schema: "Book"},
	{Name: "create_book", Schema: "Book"},
	{Name: "update_book", Schema: "Book"},
	{Name: "delete_book", Schema: "Book"},
	{Name: "publish", Schema: "Book"},
	{Name: "read_permission", Schema: "Permission"},
	{Name: "update_permission", Schema: "Permission"},
	{Name: "read_permission_group", Schema: "Permission Group"},
	{Name: "create_permission_group", Schema: "Permission Group"},
	{Name: "update_permission_group", Schema: "Permission Group"},
	{Name: "delete_permission_group", Schema: "Permission Group"},
	{Name: "read_review", Schema: "Review"},
	{Name: "create_review", Schema: "Review"},
	{Name: "update_review", Schema: "Review"},
	{Name: "read_user", Schema: "User"},
	{Name: "create_user", Schema: "User"},
	{Name: "update_user", Schema: "User"},
	{Name: "delete_user", Schema: "User"},
	{Name: "impersonate", Schema: "User"},
}

func DesiredPermissions() []string {
	names := make([]string, len(permissions))
	for i, p := range permissions {
		names[i] = p.Name
	}
	return names
}

func NewPermissionClient(drv dialect.Driver) migrategen.PermissionClient {
	return permissionClient{c: ent.NewClient(ent.Driver(drv))}
}

type permissionClient struct {
	c *ent.Client
}

func (p permissionClient) List(ctx context.Context) ([]migrategen.PermissionRow, error) {
	rows, err := p.c.Permission.Query().All(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]migrategen.PermissionRow, 0, len(rows))
	for _, row := range rows {
		out = append(out, migrategen.PermissionRow{ID: row.ID, Name: row.Name})
	}
	return out, nil
}

func (p permissionClient) CreateNames(ctx context.Context, names []string) (int, error) {
	if len(names) == 0 {
		return 0, nil
	}
	builders := make([]*ent.PermissionCreate, 0, len(names))
	for _, name := range names {
		builders = append(builders, p.c.Permission.Create().SetName(name))
	}
	created, err := p.c.Permission.CreateBulk(builders...).Save(ctx)
	if err != nil {
		return 0, err
	}
	return len(created), nil
}

func (p permissionClient) DeleteID(ctx context.Context, id int) error {
	return p.c.Permission.DeleteOneID(id).Exec(ctx)
}
