// Code generated by vent, DO NOT EDIT.

package admin

import (
	"context"
	"fmt"

	"github.com/troygilman/vent"
	ent "github.com/troygilman/vent/examples/basic/ent"
)

// SchemaAdmins holds per-schema admin surface implementations.
// A nil slot uses the generated Default*Admin for that schema.
type SchemaAdmins struct {
	AuthGroup AuthGroupAdmin

	AuthUser AuthUserAdmin
}

// AuthGroupAdmin is the customizable admin surface for AuthGroup.
// Embed DefaultAuthGroupAdmin and override only the methods you need.
//
// Field* methods supply field implementations. Validate* methods own mutation
// policy. CanRead/CanUpdate/CanDelete take the target entity. CanCreate and
// schema CRUD permissions (read_/create_/...) own schema-level access for
// routes, menu visibility, and create.
type AuthGroupAdmin interface {
	FieldName() AuthGroupField
	FieldPermissions() AuthGroupField
	Name(e *ent.AuthGroup) string
	ValidateCreate(ctx context.Context, input AuthGroupCreateInput) error
	ValidateUpdate(ctx context.Context, id int, input AuthGroupUpdateInput) error
	ValidateDelete(ctx context.Context, id int) error
	CanRead(ctx context.Context, e *ent.AuthGroup) (bool, error)
	CanCreate(ctx context.Context) (bool, error)
	CanUpdate(ctx context.Context, e *ent.AuthGroup) (bool, error)
	CanDelete(ctx context.Context, e *ent.AuthGroup) (bool, error)
}

// DefaultAuthGroupAdmin is the generated default AuthGroup admin surface.
// Embed it to keep defaults while overriding individual methods.
// Client is required for default field implementations.
type DefaultAuthGroupAdmin struct {
	Client *ent.Client
}

// NewDefaultAuthGroupAdmin returns a default AuthGroup admin using client.
func NewDefaultAuthGroupAdmin(client *ent.Client) DefaultAuthGroupAdmin {
	return DefaultAuthGroupAdmin{Client: client}
}

func (DefaultAuthGroupAdmin) Name(e *ent.AuthGroup) string {
	return fmt.Sprintf("%v", e.Name)
}

func (a DefaultAuthGroupAdmin) FieldName() AuthGroupField {
	return NewAuthGroupNameField(a.Client)
}

func (a DefaultAuthGroupAdmin) FieldPermissions() AuthGroupField {
	return NewAuthGroupPermissionsField(a.Client)
}

func (DefaultAuthGroupAdmin) ValidateCreate(context.Context, AuthGroupCreateInput) error {
	return nil
}

func (DefaultAuthGroupAdmin) ValidateUpdate(ctx context.Context, id int, input AuthGroupUpdateInput) error {
	return nil
}

func (DefaultAuthGroupAdmin) ValidateDelete(ctx context.Context, id int) error {
	return nil
}

func (DefaultAuthGroupAdmin) CanRead(ctx context.Context, _ *ent.AuthGroup) (bool, error) {
	return defaultCan(ctx, "read_auth_group")
}

func (DefaultAuthGroupAdmin) CanCreate(ctx context.Context) (bool, error) {
	return defaultCan(ctx, "create_auth_group")
}

func (DefaultAuthGroupAdmin) CanUpdate(ctx context.Context, e *ent.AuthGroup) (bool, error) {
	ok, err := defaultCan(ctx, "update_auth_group")
	if err != nil || !ok {
		return ok, err
	}
	return true, nil
}

func (DefaultAuthGroupAdmin) CanDelete(ctx context.Context, e *ent.AuthGroup) (bool, error) {
	ok, err := defaultCan(ctx, "delete_auth_group")
	if err != nil || !ok {
		return ok, err
	}
	return true, nil
}

// AuthUserAdmin is the customizable admin surface for AuthUser.
// Embed DefaultAuthUserAdmin and override only the methods you need.
//
// Field* methods supply field implementations. Validate* methods own mutation
// policy. CanRead/CanUpdate/CanDelete take the target entity. CanCreate and
// schema CRUD permissions (read_/create_/...) own schema-level access for
// routes, menu visibility, and create.
type AuthUserAdmin interface {
	FieldID() AuthUserField
	FieldEmail() AuthUserField
	FieldPassword() AuthUserField
	FieldIsStaff() AuthUserField
	FieldIsSuperuser() AuthUserField
	FieldIsActive() AuthUserField
	FieldGroups() AuthUserField
	FieldLastLogin() AuthUserField
	Name(e *ent.AuthUser) string
	ValidateCreate(ctx context.Context, input AuthUserCreateInput) error
	ValidateUpdate(ctx context.Context, id int, input AuthUserUpdateInput) error
	ValidateDelete(ctx context.Context, id int) error
	CanRead(ctx context.Context, e *ent.AuthUser) (bool, error)
	CanCreate(ctx context.Context) (bool, error)
	CanUpdate(ctx context.Context, e *ent.AuthUser) (bool, error)
	CanDelete(ctx context.Context, e *ent.AuthUser) (bool, error)
}

// DefaultAuthUserAdmin is the generated default AuthUser admin surface.
// Embed it to keep defaults while overriding individual methods.
// Client is required for default field implementations.
type DefaultAuthUserAdmin struct {
	Client *ent.Client
}

// NewDefaultAuthUserAdmin returns a default AuthUser admin using client.
func NewDefaultAuthUserAdmin(client *ent.Client) DefaultAuthUserAdmin {
	return DefaultAuthUserAdmin{Client: client}
}

func (DefaultAuthUserAdmin) Name(e *ent.AuthUser) string {
	return fmt.Sprintf("%v", e.ID)
}

func (a DefaultAuthUserAdmin) FieldID() AuthUserField {
	return NewAuthUserIdField(a.Client)
}

func (a DefaultAuthUserAdmin) FieldEmail() AuthUserField {
	return NewAuthUserEmailField(a.Client)
}

func (a DefaultAuthUserAdmin) FieldPassword() AuthUserField {
	return NewAuthUserPasswordField(a.Client)
}

func (a DefaultAuthUserAdmin) FieldIsStaff() AuthUserField {
	return NewAuthUserIsStaffField(a.Client)
}

func (a DefaultAuthUserAdmin) FieldIsSuperuser() AuthUserField {
	return NewAuthUserIsSuperuserField(a.Client)
}

func (a DefaultAuthUserAdmin) FieldIsActive() AuthUserField {
	return NewAuthUserIsActiveField(a.Client)
}

func (a DefaultAuthUserAdmin) FieldGroups() AuthUserField {
	return NewAuthUserGroupsField(a.Client)
}

func (a DefaultAuthUserAdmin) FieldLastLogin() AuthUserField {
	return NewAuthUserLastLoginField(a.Client)
}

func (DefaultAuthUserAdmin) ValidateCreate(context.Context, AuthUserCreateInput) error {
	return nil
}

func (DefaultAuthUserAdmin) ValidateUpdate(ctx context.Context, id int, input AuthUserUpdateInput) error {
	if input.IsActive != nil && !*input.IsActive {
		currentUser, err := GetUser(ctx)
		if err != nil {
			return err
		}
		if currentUser.ID == id {
			return vent.ErrCannotDeactivateSelf
		}
	}
	return nil
}

func (DefaultAuthUserAdmin) ValidateDelete(ctx context.Context, id int) error {
	currentUser, err := GetUser(ctx)
	if err != nil {
		return err
	}
	if currentUser.ID == id {
		return vent.ErrCannotDeleteSelf
	}
	return nil
}

func (DefaultAuthUserAdmin) CanRead(ctx context.Context, _ *ent.AuthUser) (bool, error) {
	return defaultCan(ctx, "read_auth_user")
}

func (DefaultAuthUserAdmin) CanCreate(ctx context.Context) (bool, error) {
	return defaultCan(ctx, "create_auth_user")
}

func (DefaultAuthUserAdmin) CanUpdate(ctx context.Context, e *ent.AuthUser) (bool, error) {
	ok, err := defaultCan(ctx, "update_auth_user")
	if err != nil || !ok {
		return ok, err
	}
	return allowSuperuserMutation(ctx, e)
}

func (DefaultAuthUserAdmin) CanDelete(ctx context.Context, e *ent.AuthUser) (bool, error) {
	ok, err := defaultCan(ctx, "delete_auth_user")
	if err != nil || !ok {
		return ok, err
	}
	currentUser, err := GetUser(ctx)
	if err != nil {
		return false, err
	}
	if currentUser.ID == e.ID {
		return false, nil
	}
	return allowSuperuserMutation(ctx, e)
}

func defaultCan(ctx context.Context, permission string) (bool, error) {
	user, err := GetUser(ctx)
	if err != nil {
		return false, err
	}
	return UserHasPermission(ctx, user, permission)
}

func denyIfCannot(ok bool, err error) error {
	if err != nil {
		return err
	}
	if !ok {
		return vent.Forbidden("forbidden")
	}
	return nil
}

func allowSuperuserMutation(ctx context.Context, target *ent.AuthUser) (bool, error) {
	currentUser, err := GetUser(ctx)
	if err != nil {
		return false, err
	}
	return currentUser.IsSuperuser || !target.IsSuperuser, nil
}
