// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/troygilman/vent/examples/basic/ent/authgroup"
	"github.com/troygilman/vent/examples/basic/ent/authuser"
	"github.com/troygilman/vent/examples/basic/ent/predicate"
)

// AuthUserUpdate is the builder for updating AuthUser entities.
type AuthUserUpdate struct {
	config
	hooks    []Hook
	mutation *AuthUserMutation
}

// Where appends a list predicates to the AuthUserUpdate builder.
func (_u *AuthUserUpdate) Where(ps ...predicate.AuthUser) *AuthUserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEmail sets the "email" field.
func (_u *AuthUserUpdate) SetEmail(v string) *AuthUserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *AuthUserUpdate) SetNillableEmail(v *string) *AuthUserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *AuthUserUpdate) SetPasswordHash(v string) *AuthUserUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *AuthUserUpdate) SetNillablePasswordHash(v *string) *AuthUserUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// ClearPasswordHash clears the value of the "password_hash" field.
func (_u *AuthUserUpdate) ClearPasswordHash() *AuthUserUpdate {
	_u.mutation.ClearPasswordHash()
	return _u
}

// SetIsStaff sets the "is_staff" field.
func (_u *AuthUserUpdate) SetIsStaff(v bool) *AuthUserUpdate {
	_u.mutation.SetIsStaff(v)
	return _u
}

// SetNillableIsStaff sets the "is_staff" field if the given value is not nil.
func (_u *AuthUserUpdate) SetNillableIsStaff(v *bool) *AuthUserUpdate {
	if v != nil {
		_u.SetIsStaff(*v)
	}
	return _u
}

// SetIsSuperuser sets the "is_superuser" field.
func (_u *AuthUserUpdate) SetIsSuperuser(v bool) *AuthUserUpdate {
	_u.mutation.SetIsSuperuser(v)
	return _u
}

// SetNillableIsSuperuser sets the "is_superuser" field if the given value is not nil.
func (_u *AuthUserUpdate) SetNillableIsSuperuser(v *bool) *AuthUserUpdate {
	if v != nil {
		_u.SetIsSuperuser(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *AuthUserUpdate) SetIsActive(v bool) *AuthUserUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *AuthUserUpdate) SetNillableIsActive(v *bool) *AuthUserUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetLastLogin sets the "last_login" field.
func (_u *AuthUserUpdate) SetLastLogin(v time.Time) *AuthUserUpdate {
	_u.mutation.SetLastLogin(v)
	return _u
}

// SetNillableLastLogin sets the "last_login" field if the given value is not nil.
func (_u *AuthUserUpdate) SetNillableLastLogin(v *time.Time) *AuthUserUpdate {
	if v != nil {
		_u.SetLastLogin(*v)
	}
	return _u
}

// ClearLastLogin clears the value of the "last_login" field.
func (_u *AuthUserUpdate) ClearLastLogin() *AuthUserUpdate {
	_u.mutation.ClearLastLogin()
	return _u
}

// AddGroupIDs adds the "groups" edge to the AuthGroup entity by IDs.
func (_u *AuthUserUpdate) AddGroupIDs(ids ...int) *AuthUserUpdate {
	_u.mutation.AddGroupIDs(ids...)
	return _u
}

// AddGroups adds the "groups" edges to the AuthGroup entity.
func (_u *AuthUserUpdate) AddGroups(v ...*AuthGroup) *AuthUserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupIDs(ids...)
}

// Mutation returns the AuthUserMutation object of the builder.
func (_u *AuthUserUpdate) Mutation() *AuthUserMutation {
	return _u.mutation
}

// ClearGroups clears all "groups" edges to the AuthGroup entity.
func (_u *AuthUserUpdate) ClearGroups() *AuthUserUpdate {
	_u.mutation.ClearGroups()
	return _u
}

// RemoveGroupIDs removes the "groups" edge to AuthGroup entities by IDs.
func (_u *AuthUserUpdate) RemoveGroupIDs(ids ...int) *AuthUserUpdate {
	_u.mutation.RemoveGroupIDs(ids...)
	return _u
}

// RemoveGroups removes "groups" edges to AuthGroup entities.
func (_u *AuthUserUpdate) RemoveGroups(v ...*AuthGroup) *AuthUserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuthUserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthUserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuthUserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthUserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuthUserUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := authuser.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "AuthUser.email": %w`, err)}
		}
	}
	return nil
}

func (_u *AuthUserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authuser.Table, authuser.Columns, sqlgraph.NewFieldSpec(authuser.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(authuser.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(authuser.FieldPasswordHash, field.TypeString, value)
	}
	if _u.mutation.PasswordHashCleared() {
		_spec.ClearField(authuser.FieldPasswordHash, field.TypeString)
	}
	if value, ok := _u.mutation.IsStaff(); ok {
		_spec.SetField(authuser.FieldIsStaff, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsSuperuser(); ok {
		_spec.SetField(authuser.FieldIsSuperuser, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(authuser.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastLogin(); ok {
		_spec.SetField(authuser.FieldLastLogin, field.TypeTime, value)
	}
	if _u.mutation.LastLoginCleared() {
		_spec.ClearField(authuser.FieldLastLogin, field.TypeTime)
	}
	if _u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   authuser.GroupsTable,
			Columns: authuser.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(authgroup.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !_u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   authuser.GroupsTable,
			Columns: authuser.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(authgroup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   authuser.GroupsTable,
			Columns: authuser.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(authgroup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuthUserUpdateOne is the builder for updating a single AuthUser entity.
type AuthUserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthUserMutation
}

// SetEmail sets the "email" field.
func (_u *AuthUserUpdateOne) SetEmail(v string) *AuthUserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *AuthUserUpdateOne) SetNillableEmail(v *string) *AuthUserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *AuthUserUpdateOne) SetPasswordHash(v string) *AuthUserUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *AuthUserUpdateOne) SetNillablePasswordHash(v *string) *AuthUserUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// ClearPasswordHash clears the value of the "password_hash" field.
func (_u *AuthUserUpdateOne) ClearPasswordHash() *AuthUserUpdateOne {
	_u.mutation.ClearPasswordHash()
	return _u
}

// SetIsStaff sets the "is_staff" field.
func (_u *AuthUserUpdateOne) SetIsStaff(v bool) *AuthUserUpdateOne {
	_u.mutation.SetIsStaff(v)
	return _u
}

// SetNillableIsStaff sets the "is_staff" field if the given value is not nil.
func (_u *AuthUserUpdateOne) SetNillableIsStaff(v *bool) *AuthUserUpdateOne {
	if v != nil {
		_u.SetIsStaff(*v)
	}
	return _u
}

// SetIsSuperuser sets the "is_superuser" field.
func (_u *AuthUserUpdateOne) SetIsSuperuser(v bool) *AuthUserUpdateOne {
	_u.mutation.SetIsSuperuser(v)
	return _u
}

// SetNillableIsSuperuser sets the "is_superuser" field if the given value is not nil.
func (_u *AuthUserUpdateOne) SetNillableIsSuperuser(v *bool) *AuthUserUpdateOne {
	if v != nil {
		_u.SetIsSuperuser(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *AuthUserUpdateOne) SetIsActive(v bool) *AuthUserUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *AuthUserUpdateOne) SetNillableIsActive(v *bool) *AuthUserUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetLastLogin sets the "last_login" field.
func (_u *AuthUserUpdateOne) SetLastLogin(v time.Time) *AuthUserUpdateOne {
	_u.mutation.SetLastLogin(v)
	return _u
}

// SetNillableLastLogin sets the "last_login" field if the given value is not nil.
func (_u *AuthUserUpdateOne) SetNillableLastLogin(v *time.Time) *AuthUserUpdateOne {
	if v != nil {
		_u.SetLastLogin(*v)
	}
	return _u
}

// ClearLastLogin clears the value of the "last_login" field.
func (_u *AuthUserUpdateOne) ClearLastLogin() *AuthUserUpdateOne {
	_u.mutation.ClearLastLogin()
	return _u
}

// AddGroupIDs adds the "groups" edge to the AuthGroup entity by IDs.
func (_u *AuthUserUpdateOne) AddGroupIDs(ids ...int) *AuthUserUpdateOne {
	_u.mutation.AddGroupIDs(ids...)
	return _u
}

// AddGroups adds the "groups" edges to the AuthGroup entity.
func (_u *AuthUserUpdateOne) AddGroups(v ...*AuthGroup) *AuthUserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupIDs(ids...)
}

// Mutation returns the AuthUserMutation object of the builder.
func (_u *AuthUserUpdateOne) Mutation() *AuthUserMutation {
	return _u.mutation
}

// ClearGroups clears all "groups" edges to the AuthGroup entity.
func (_u *AuthUserUpdateOne) ClearGroups() *AuthUserUpdateOne {
	_u.mutation.ClearGroups()
	return _u
}

// RemoveGroupIDs removes the "groups" edge to AuthGroup entities by IDs.
func (_u *AuthUserUpdateOne) RemoveGroupIDs(ids ...int) *AuthUserUpdateOne {
	_u.mutation.RemoveGroupIDs(ids...)
	return _u
}

// RemoveGroups removes "groups" edges to AuthGroup entities.
func (_u *AuthUserUpdateOne) RemoveGroups(v ...*AuthGroup) *AuthUserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupIDs(ids...)
}

// Where appends a list predicates to the AuthUserUpdate builder.
func (_u *AuthUserUpdateOne) Where(ps ...predicate.AuthUser) *AuthUserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuthUserUpdateOne) Select(field string, fields ...string) *AuthUserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuthUser entity.
func (_u *AuthUserUpdateOne) Save(ctx context.Context) (*AuthUser, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthUserUpdateOne) SaveX(ctx context.Context) *AuthUser {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuthUserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthUserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuthUserUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := authuser.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "AuthUser.email": %w`, err)}
		}
	}
	return nil
}

func (_u *AuthUserUpdateOne) sqlSave(ctx context.Context) (_node *AuthUser, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authuser.Table, authuser.Columns, sqlgraph.NewFieldSpec(authuser.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuthUser.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authuser.FieldID)
		for _, f := range fields {
			if !authuser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != authuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(authuser.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(authuser.FieldPasswordHash, field.TypeString, value)
	}
	if _u.mutation.PasswordHashCleared() {
		_spec.ClearField(authuser.FieldPasswordHash, field.TypeString)
	}
	if value, ok := _u.mutation.IsStaff(); ok {
		_spec.SetField(authuser.FieldIsStaff, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsSuperuser(); ok {
		_spec.SetField(authuser.FieldIsSuperuser, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(authuser.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastLogin(); ok {
		_spec.SetField(authuser.FieldLastLogin, field.TypeTime, value)
	}
	if _u.mutation.LastLoginCleared() {
		_spec.ClearField(authuser.FieldLastLogin, field.TypeTime)
	}
	if _u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   authuser.GroupsTable,
			Columns: authuser.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(authgroup.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !_u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   authuser.GroupsTable,
			Columns: authuser.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(authgroup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   authuser.GroupsTable,
			Columns: authuser.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(authgroup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AuthUser{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
