// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/troygilman/vent/examples/basic/ent/author"
	"github.com/troygilman/vent/examples/basic/ent/book"
	"github.com/troygilman/vent/examples/basic/ent/category"
	"github.com/troygilman/vent/examples/basic/ent/predicate"
	"github.com/troygilman/vent/examples/basic/ent/review"
	"github.com/troygilman/vent/examples/basic/ent/tag"
)

// BookUpdate is the builder for updating Book entities.
type BookUpdate struct {
	config
	hooks    []Hook
	mutation *BookMutation
}

// Where appends a list predicates to the BookUpdate builder.
func (_u *BookUpdate) Where(ps ...predicate.Book) *BookUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *BookUpdate) SetTitle(v string) *BookUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BookUpdate) SetNillableTitle(v *string) *BookUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetIsbn sets the "isbn" field.
func (_u *BookUpdate) SetIsbn(v string) *BookUpdate {
	_u.mutation.SetIsbn(v)
	return _u
}

// SetNillableIsbn sets the "isbn" field if the given value is not nil.
func (_u *BookUpdate) SetNillableIsbn(v *string) *BookUpdate {
	if v != nil {
		_u.SetIsbn(*v)
	}
	return _u
}

// ClearIsbn clears the value of the "isbn" field.
func (_u *BookUpdate) ClearIsbn() *BookUpdate {
	_u.mutation.ClearIsbn()
	return _u
}

// SetPages sets the "pages" field.
func (_u *BookUpdate) SetPages(v int) *BookUpdate {
	_u.mutation.ResetPages()
	_u.mutation.SetPages(v)
	return _u
}

// SetNillablePages sets the "pages" field if the given value is not nil.
func (_u *BookUpdate) SetNillablePages(v *int) *BookUpdate {
	if v != nil {
		_u.SetPages(*v)
	}
	return _u
}

// AddPages adds value to the "pages" field.
func (_u *BookUpdate) AddPages(v int) *BookUpdate {
	_u.mutation.AddPages(v)
	return _u
}

// SetPrice sets the "price" field.
func (_u *BookUpdate) SetPrice(v float64) *BookUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *BookUpdate) SetNillablePrice(v *float64) *BookUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *BookUpdate) AddPrice(v float64) *BookUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// SetPublished sets the "published" field.
func (_u *BookUpdate) SetPublished(v bool) *BookUpdate {
	_u.mutation.SetPublished(v)
	return _u
}

// SetNillablePublished sets the "published" field if the given value is not nil.
func (_u *BookUpdate) SetNillablePublished(v *bool) *BookUpdate {
	if v != nil {
		_u.SetPublished(*v)
	}
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *BookUpdate) SetPublishedAt(v time.Time) *BookUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *BookUpdate) SetNillablePublishedAt(v *time.Time) *BookUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *BookUpdate) ClearPublishedAt() *BookUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetViewCount sets the "view_count" field.
func (_u *BookUpdate) SetViewCount(v int) *BookUpdate {
	_u.mutation.ResetViewCount()
	_u.mutation.SetViewCount(v)
	return _u
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_u *BookUpdate) SetNillableViewCount(v *int) *BookUpdate {
	if v != nil {
		_u.SetViewCount(*v)
	}
	return _u
}

// AddViewCount adds value to the "view_count" field.
func (_u *BookUpdate) AddViewCount(v int) *BookUpdate {
	_u.mutation.AddViewCount(v)
	return _u
}

// SetInternalNotes sets the "internal_notes" field.
func (_u *BookUpdate) SetInternalNotes(v string) *BookUpdate {
	_u.mutation.SetInternalNotes(v)
	return _u
}

// SetNillableInternalNotes sets the "internal_notes" field if the given value is not nil.
func (_u *BookUpdate) SetNillableInternalNotes(v *string) *BookUpdate {
	if v != nil {
		_u.SetInternalNotes(*v)
	}
	return _u
}

// ClearInternalNotes clears the value of the "internal_notes" field.
func (_u *BookUpdate) ClearInternalNotes() *BookUpdate {
	_u.mutation.ClearInternalNotes()
	return _u
}

// SetAuthorID sets the "author" edge to the Author entity by ID.
func (_u *BookUpdate) SetAuthorID(id int) *BookUpdate {
	_u.mutation.SetAuthorID(id)
	return _u
}

// SetAuthor sets the "author" edge to the Author entity.
func (_u *BookUpdate) SetAuthor(v *Author) *BookUpdate {
	return _u.SetAuthorID(v.ID)
}

// SetCategoryID sets the "category" edge to the Category entity by ID.
func (_u *BookUpdate) SetCategoryID(id int) *BookUpdate {
	_u.mutation.SetCategoryID(id)
	return _u
}

// SetNillableCategoryID sets the "category" edge to the Category entity by ID if the given value is not nil.
func (_u *BookUpdate) SetNillableCategoryID(id *int) *BookUpdate {
	if id != nil {
		_u = _u.SetCategoryID(*id)
	}
	return _u
}

// SetCategory sets the "category" edge to the Category entity.
func (_u *BookUpdate) SetCategory(v *Category) *BookUpdate {
	return _u.SetCategoryID(v.ID)
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (_u *BookUpdate) AddTagIDs(ids ...int) *BookUpdate {
	_u.mutation.AddTagIDs(ids...)
	return _u
}

// AddTags adds the "tags" edges to the Tag entity.
func (_u *BookUpdate) AddTags(v ...*Tag) *BookUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTagIDs(ids...)
}

// AddReviewIDs adds the "reviews" edge to the Review entity by IDs.
func (_u *BookUpdate) AddReviewIDs(ids ...int) *BookUpdate {
	_u.mutation.AddReviewIDs(ids...)
	return _u
}

// AddReviews adds the "reviews" edges to the Review entity.
func (_u *BookUpdate) AddReviews(v ...*Review) *BookUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReviewIDs(ids...)
}

// Mutation returns the BookMutation object of the builder.
func (_u *BookUpdate) Mutation() *BookMutation {
	return _u.mutation
}

// ClearAuthor clears the "author" edge to the Author entity.
func (_u *BookUpdate) ClearAuthor() *BookUpdate {
	_u.mutation.ClearAuthor()
	return _u
}

// ClearCategory clears the "category" edge to the Category entity.
func (_u *BookUpdate) ClearCategory() *BookUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// ClearTags clears all "tags" edges to the Tag entity.
func (_u *BookUpdate) ClearTags() *BookUpdate {
	_u.mutation.ClearTags()
	return _u
}

// RemoveTagIDs removes the "tags" edge to Tag entities by IDs.
func (_u *BookUpdate) RemoveTagIDs(ids ...int) *BookUpdate {
	_u.mutation.RemoveTagIDs(ids...)
	return _u
}

// RemoveTags removes "tags" edges to Tag entities.
func (_u *BookUpdate) RemoveTags(v ...*Tag) *BookUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTagIDs(ids...)
}

// ClearReviews clears all "reviews" edges to the Review entity.
func (_u *BookUpdate) ClearReviews() *BookUpdate {
	_u.mutation.ClearReviews()
	return _u
}

// RemoveReviewIDs removes the "reviews" edge to Review entities by IDs.
func (_u *BookUpdate) RemoveReviewIDs(ids ...int) *BookUpdate {
	_u.mutation.RemoveReviewIDs(ids...)
	return _u
}

// RemoveReviews removes "reviews" edges to Review entities.
func (_u *BookUpdate) RemoveReviews(v ...*Review) *BookUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReviewIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BookUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BookUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BookUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := book.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Book.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Pages(); ok {
		if err := book.PagesValidator(v); err != nil {
			return &ValidationError{Name: "pages", err: fmt.Errorf(`ent: validator failed for field "Book.pages": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Price(); ok {
		if err := book.PriceValidator(v); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`ent: validator failed for field "Book.price": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ViewCount(); ok {
		if err := book.ViewCountValidator(v); err != nil {
			return &ValidationError{Name: "view_count", err: fmt.Errorf(`ent: validator failed for field "Book.view_count": %w`, err)}
		}
	}
	if _u.mutation.AuthorCleared() && len(_u.mutation.AuthorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Book.author"`)
	}
	return nil
}

func (_u *BookUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(book.Table, book.Columns, sqlgraph.NewFieldSpec(book.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(book.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Isbn(); ok {
		_spec.SetField(book.FieldIsbn, field.TypeString, value)
	}
	if _u.mutation.IsbnCleared() {
		_spec.ClearField(book.FieldIsbn, field.TypeString)
	}
	if value, ok := _u.mutation.Pages(); ok {
		_spec.SetField(book.FieldPages, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPages(); ok {
		_spec.AddField(book.FieldPages, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(book.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(book.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Published(); ok {
		_spec.SetField(book.FieldPublished, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(book.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(book.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ViewCount(); ok {
		_spec.SetField(book.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedViewCount(); ok {
		_spec.AddField(book.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.InternalNotes(); ok {
		_spec.SetField(book.FieldInternalNotes, field.TypeString, value)
	}
	if _u.mutation.InternalNotesCleared() {
		_spec.ClearField(book.FieldInternalNotes, field.TypeString)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   book.AuthorTable,
			Columns: []string{book.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(author.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   book.AuthorTable,
			Columns: []string{book.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(author.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   book.CategoryTable,
			Columns: []string{book.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   book.CategoryTable,
			Columns: []string{book.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.TagsTable,
			Columns: book.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTagsIDs(); len(nodes) > 0 && !_u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.TagsTable,
			Columns: book.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.TagsTable,
			Columns: book.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReviewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.ReviewsTable,
			Columns: []string{book.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReviewsIDs(); len(nodes) > 0 && !_u.mutation.ReviewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.ReviewsTable,
			Columns: []string{book.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.ReviewsTable,
			Columns: []string{book.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{book.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BookUpdateOne is the builder for updating a single Book entity.
type BookUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BookMutation
}

// SetTitle sets the "title" field.
func (_u *BookUpdateOne) SetTitle(v string) *BookUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableTitle(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetIsbn sets the "isbn" field.
func (_u *BookUpdateOne) SetIsbn(v string) *BookUpdateOne {
	_u.mutation.SetIsbn(v)
	return _u
}

// SetNillableIsbn sets the "isbn" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableIsbn(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetIsbn(*v)
	}
	return _u
}

// ClearIsbn clears the value of the "isbn" field.
func (_u *BookUpdateOne) ClearIsbn() *BookUpdateOne {
	_u.mutation.ClearIsbn()
	return _u
}

// SetPages sets the "pages" field.
func (_u *BookUpdateOne) SetPages(v int) *BookUpdateOne {
	_u.mutation.ResetPages()
	_u.mutation.SetPages(v)
	return _u
}

// SetNillablePages sets the "pages" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillablePages(v *int) *BookUpdateOne {
	if v != nil {
		_u.SetPages(*v)
	}
	return _u
}

// AddPages adds value to the "pages" field.
func (_u *BookUpdateOne) AddPages(v int) *BookUpdateOne {
	_u.mutation.AddPages(v)
	return _u
}

// SetPrice sets the "price" field.
func (_u *BookUpdateOne) SetPrice(v float64) *BookUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillablePrice(v *float64) *BookUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *BookUpdateOne) AddPrice(v float64) *BookUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// SetPublished sets the "published" field.
func (_u *BookUpdateOne) SetPublished(v bool) *BookUpdateOne {
	_u.mutation.SetPublished(v)
	return _u
}

// SetNillablePublished sets the "published" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillablePublished(v *bool) *BookUpdateOne {
	if v != nil {
		_u.SetPublished(*v)
	}
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *BookUpdateOne) SetPublishedAt(v time.Time) *BookUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillablePublishedAt(v *time.Time) *BookUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *BookUpdateOne) ClearPublishedAt() *BookUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetViewCount sets the "view_count" field.
func (_u *BookUpdateOne) SetViewCount(v int) *BookUpdateOne {
	_u.mutation.ResetViewCount()
	_u.mutation.SetViewCount(v)
	return _u
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableViewCount(v *int) *BookUpdateOne {
	if v != nil {
		_u.SetViewCount(*v)
	}
	return _u
}

// AddViewCount adds value to the "view_count" field.
func (_u *BookUpdateOne) AddViewCount(v int) *BookUpdateOne {
	_u.mutation.AddViewCount(v)
	return _u
}

// SetInternalNotes sets the "internal_notes" field.
func (_u *BookUpdateOne) SetInternalNotes(v string) *BookUpdateOne {
	_u.mutation.SetInternalNotes(v)
	return _u
}

// SetNillableInternalNotes sets the "internal_notes" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableInternalNotes(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetInternalNotes(*v)
	}
	return _u
}

// ClearInternalNotes clears the value of the "internal_notes" field.
func (_u *BookUpdateOne) ClearInternalNotes() *BookUpdateOne {
	_u.mutation.ClearInternalNotes()
	return _u
}

// SetAuthorID sets the "author" edge to the Author entity by ID.
func (_u *BookUpdateOne) SetAuthorID(id int) *BookUpdateOne {
	_u.mutation.SetAuthorID(id)
	return _u
}

// SetAuthor sets the "author" edge to the Author entity.
func (_u *BookUpdateOne) SetAuthor(v *Author) *BookUpdateOne {
	return _u.SetAuthorID(v.ID)
}

// SetCategoryID sets the "category" edge to the Category entity by ID.
func (_u *BookUpdateOne) SetCategoryID(id int) *BookUpdateOne {
	_u.mutation.SetCategoryID(id)
	return _u
}

// SetNillableCategoryID sets the "category" edge to the Category entity by ID if the given value is not nil.
func (_u *BookUpdateOne) SetNillableCategoryID(id *int) *BookUpdateOne {
	if id != nil {
		_u = _u.SetCategoryID(*id)
	}
	return _u
}

// SetCategory sets the "category" edge to the Category entity.
func (_u *BookUpdateOne) SetCategory(v *Category) *BookUpdateOne {
	return _u.SetCategoryID(v.ID)
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (_u *BookUpdateOne) AddTagIDs(ids ...int) *BookUpdateOne {
	_u.mutation.AddTagIDs(ids...)
	return _u
}

// AddTags adds the "tags" edges to the Tag entity.
func (_u *BookUpdateOne) AddTags(v ...*Tag) *BookUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTagIDs(ids...)
}

// AddReviewIDs adds the "reviews" edge to the Review entity by IDs.
func (_u *BookUpdateOne) AddReviewIDs(ids ...int) *BookUpdateOne {
	_u.mutation.AddReviewIDs(ids...)
	return _u
}

// AddReviews adds the "reviews" edges to the Review entity.
func (_u *BookUpdateOne) AddReviews(v ...*Review) *BookUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReviewIDs(ids...)
}

// Mutation returns the BookMutation object of the builder.
func (_u *BookUpdateOne) Mutation() *BookMutation {
	return _u.mutation
}

// ClearAuthor clears the "author" edge to the Author entity.
func (_u *BookUpdateOne) ClearAuthor() *BookUpdateOne {
	_u.mutation.ClearAuthor()
	return _u
}

// ClearCategory clears the "category" edge to the Category entity.
func (_u *BookUpdateOne) ClearCategory() *BookUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// ClearTags clears all "tags" edges to the Tag entity.
func (_u *BookUpdateOne) ClearTags() *BookUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// RemoveTagIDs removes the "tags" edge to Tag entities by IDs.
func (_u *BookUpdateOne) RemoveTagIDs(ids ...int) *BookUpdateOne {
	_u.mutation.RemoveTagIDs(ids...)
	return _u
}

// RemoveTags removes "tags" edges to Tag entities.
func (_u *BookUpdateOne) RemoveTags(v ...*Tag) *BookUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTagIDs(ids...)
}

// ClearReviews clears all "reviews" edges to the Review entity.
func (_u *BookUpdateOne) ClearReviews() *BookUpdateOne {
	_u.mutation.ClearReviews()
	return _u
}

// RemoveReviewIDs removes the "reviews" edge to Review entities by IDs.
func (_u *BookUpdateOne) RemoveReviewIDs(ids ...int) *BookUpdateOne {
	_u.mutation.RemoveReviewIDs(ids...)
	return _u
}

// RemoveReviews removes "reviews" edges to Review entities.
func (_u *BookUpdateOne) RemoveReviews(v ...*Review) *BookUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReviewIDs(ids...)
}

// Where appends a list predicates to the BookUpdate builder.
func (_u *BookUpdateOne) Where(ps ...predicate.Book) *BookUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BookUpdateOne) Select(field string, fields ...string) *BookUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Book entity.
func (_u *BookUpdateOne) Save(ctx context.Context) (*Book, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookUpdateOne) SaveX(ctx context.Context) *Book {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BookUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BookUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := book.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Book.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Pages(); ok {
		if err := book.PagesValidator(v); err != nil {
			return &ValidationError{Name: "pages", err: fmt.Errorf(`ent: validator failed for field "Book.pages": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Price(); ok {
		if err := book.PriceValidator(v); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`ent: validator failed for field "Book.price": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ViewCount(); ok {
		if err := book.ViewCountValidator(v); err != nil {
			return &ValidationError{Name: "view_count", err: fmt.Errorf(`ent: validator failed for field "Book.view_count": %w`, err)}
		}
	}
	if _u.mutation.AuthorCleared() && len(_u.mutation.AuthorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Book.author"`)
	}
	return nil
}

func (_u *BookUpdateOne) sqlSave(ctx context.Context) (_node *Book, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(book.Table, book.Columns, sqlgraph.NewFieldSpec(book.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Book.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, book.FieldID)
		for _, f := range fields {
			if !book.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != book.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(book.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Isbn(); ok {
		_spec.SetField(book.FieldIsbn, field.TypeString, value)
	}
	if _u.mutation.IsbnCleared() {
		_spec.ClearField(book.FieldIsbn, field.TypeString)
	}
	if value, ok := _u.mutation.Pages(); ok {
		_spec.SetField(book.FieldPages, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPages(); ok {
		_spec.AddField(book.FieldPages, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(book.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(book.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Published(); ok {
		_spec.SetField(book.FieldPublished, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(book.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(book.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ViewCount(); ok {
		_spec.SetField(book.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedViewCount(); ok {
		_spec.AddField(book.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.InternalNotes(); ok {
		_spec.SetField(book.FieldInternalNotes, field.TypeString, value)
	}
	if _u.mutation.InternalNotesCleared() {
		_spec.ClearField(book.FieldInternalNotes, field.TypeString)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   book.AuthorTable,
			Columns: []string{book.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(author.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   book.AuthorTable,
			Columns: []string{book.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(author.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   book.CategoryTable,
			Columns: []string{book.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   book.CategoryTable,
			Columns: []string{book.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.TagsTable,
			Columns: book.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTagsIDs(); len(nodes) > 0 && !_u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.TagsTable,
			Columns: book.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.TagsTable,
			Columns: book.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReviewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.ReviewsTable,
			Columns: []string{book.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReviewsIDs(); len(nodes) > 0 && !_u.mutation.ReviewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.ReviewsTable,
			Columns: []string{book.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.ReviewsTable,
			Columns: []string{book.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Book{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{book.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
